version: '3'
services:
  mongo-db-services:
  #Using the latest version of mongodb
    image: mongo:latest
    container_name: mongo-db-services
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    #ports:
      #- 27017:27017
    volumes:
      - ./data:/data/db
  mongo-express-services:
  #using Version : 1.0.2-18-alpine3.19
    image: mongo-express:1.0.2-18-alpine3.19
    restart: always
    container_name: mongo-express-services
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db-services
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8888:8888
    volumes:
      - ./data:/data/db
    depends_on:
      - mongo-db-services
